version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
    restart: always
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
       - data:/var/lib/postgresql/data
    restart: always     

volumes:
  data: 